-- Economía Hogar · esquema para Supabase
-- 1) Ejecuta este SQL en SQL Editor dentro de tu proyecto Supabase

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  fecha date not null,
  concepto text not null,
  categoria text not null,
  tipo text not null check (tipo in ('Fijo', 'Variable')),
  importe numeric(10,2) not null,
  creado_por text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.budgets (
  categoria text primary key,
  presupuesto numeric(10,2) not null default 0,
  updated_at timestamptz default now()
);

alter table public.expenses enable row level security;
alter table public.budgets enable row level security;

-- Política simple para un hogar compartido:
-- cualquier usuario autenticado puede leer, crear, editar y borrar.
create policy if not exists "authenticated can read expenses"
  on public.expenses for select to authenticated using (true);
create policy if not exists "authenticated can insert expenses"
  on public.expenses for insert to authenticated with check (true);
create policy if not exists "authenticated can update expenses"
  on public.expenses for update to authenticated using (true) with check (true);
create policy if not exists "authenticated can delete expenses"
  on public.expenses for delete to authenticated using (true);

create policy if not exists "authenticated can read budgets"
  on public.budgets for select to authenticated using (true);
create policy if not exists "authenticated can write budgets"
  on public.budgets for all to authenticated using (true) with check (true);

insert into public.budgets (categoria, presupuesto) values
  ('Supermercado', 0),
  ('Ropa', 0),
  ('Extrascolares', 0),
  ('Guardería / Comedor', 0),
  ('Ocio', 0),
  ('Luz', 0),
  ('Internet', 0),
  ('Comunidad', 0),
  ('Seguro', 0),
  ('Transporte / Coche', 0),
  ('Otros', 0)
on conflict (categoria) do nothing;
